[package]
name = "bench_pwd_hash"
version = "0.1.0"
edition = "2024"

[dependencies]
pbkdf2 = "0.12.2"
sha2 = "0.10.8"
rayon = "1.10.0"
argon2 = "0.5.3"
rand = "0.9.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench"
harness = false
